### ISSUE TITLE
How to obtain an oauth verifier without a public callback url

### ISSUE THREAD

**Issue by henrypenny** [JohnDeere/MyJohnDeereAPI-OAuth-PHP-Client#5]
I'm testing this API on my local env and I don't currently have a public callback url. Is there another way to obtain an oauth verifier?

**Comment by mp18735** [comment]
@henrypenny you can use localhost with port you are using something like http://localhost:80/callback

**Comment by henrypenny** [comment]
Thanks, that works. Does it not need to be visible outside of my local machine?

**Comment by mp18735** [comment]
Not needed. Unless you host it on website.

**Comment by henrypenny** [comment]
Many thanks.

**Comment by mp18735** [comment]
@henrypenny Hope you are making progress with the sample code. To explain it in detail localhost callback URL only works in your local code, once you deploy this to web application then you need to use public URL instead of localhost. If you are using standalone application then i would recommend to use "oob" which involves manual process to generate verifier.
